name: Mirror to Bitbucket

on:
  push:
    branches:
      - canary-dev

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add upstream Remote
        run: |
          git remote add upstream git@github.com:Assets-MFB/mifosx-cba-backend.git
          git fetch upstream --prune

      - name: Mirror to Bitbucket
        run: |
          git push --mirror upstream