name: Mirror to Github

on:
  push:
    branches:
      - test/cleanup-ci

jobs:
  mirror:
    if: github.repository == 'fitercanary/fineract-template'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}